### ISSUE TITLE
How to get the values?

### ISSUE THREAD

**Issue by skalero01** [bakerkretzmar/nova-settings-tool#13]
Hi, how can i get the saved value without making a call to Valuestore, do you have some class or something?

Something like this its what i imaging: `NovaSettings::getValue('facebook_url')`

Regards

**Comment by bakerkretzmar** [comment]
This package doesn't provide a global settings helper, but you can set up your own really easily. Tim MacDonald's [Global Application Settings](https://laravel-news.com/global-application-settings) article explains how to do that, that's what I did and what gave me the idea for the package!
