### ISSUE TITLE
Support for standard Nova fields

### ISSUE THREAD

**Issue by f-liva** [bakerkretzmar/nova-settings-tool#14]
Any chance to get that? It's complicated? Can I help?

**Comment by bakerkretzmar** [comment]
I think the Nova fields are too tightly integrated into Nova to actually use the components themselves, but I'm open to adding different field types, or PRs for anything! Were there particular field types you were interested in?

**Comment by f-liva** [comment]
For sure the code editor, selects and date fields

**Comment by FabioWidmer** [comment]
I just created a pull request to add support for a single file input type: #19

**Comment by ghost** [comment]
Do you think it will be possible to add a password fieldtype?

**Comment by bakerkretzmar** [comment]
@GuidoThomassen I'm hesitant about that because I don't know what the security implications might be, but feel free to submit a PR!

@fede91it `code` type has been added, `select` is coming in v1, and `date` is planned.
