### ISSUE TITLE
How can "toggle" be set to true as default?

### ISSUE THREAD

**Issue by michapixel** [bakerkretzmar/nova-settings-tool#17]

**Comment by bakerkretzmar** [comment]
Just added this! Set `'default' => true` for the Toggle settings you want on by default.

**Comment by michapixel** [comment]
Very nice!
The toggle works as promised, but textfields/Textareas do not (didn't try checkboxes and radios or selects/options), 
unless there is another way like what i did:
```
default -> nada
value -> nada
text -> nada
html -> nada
```

**Comment by bakerkretzmar** [comment]
Didn't even think to expand this to the other setting types, will do.

**Comment by bakerkretzmar** [comment]
I'm rethinking this actually, since this package's goal isn't to handle the settings themselves in your app, just make a nice gui for them in Nova. With the toggle for example, setting `default => true` actually _doesn't affect the value of the setting in the JSON_, only what gets displayed on the tool. This actually strikes me as pretty confusing.

@michapixel thoughts?

**Comment by michapixel** [comment]
My standpoint would be:

Not all settings possible should be covered by this tool, but the most
basic things, like checkbox/toggle, input (single line), input numbers (int
and decimal), Multiline text, image field, icon field (fontawesome,
customizable?)
And for complex one's I'd suggest json-editor (
https://github.com/josdejong/jsoneditor/blob/develop/README.md)

Beware, I'm on vacation this week and the next, and after that i might be
working on some other thing the first days, but I'll try to help, as i
think this might be very handsome in every project.

Let me know what you think.

Jacob Baker-Kretzmar <notifications@github.com> schrieb am Sa., 27. Juli
2019, 21:38:

**Comment by bakerkretzmar** [comment]
@michapixel thanks for your input. I'm going to revert this in v1, I think it's safer to keep the presentation of the settings and their values firmly separate, if a setting needs to be 'on' or some other value by default, you should configure that where you're consuming the setting value or just manually set it to your desired default when you add it.
