### ISSUE TITLE
Single file input

### ISSUE THREAD

**Issue by Atnaize** [bakerkretzmar/nova-settings-tool#22]
Hey, 

Thank you for your package, it's very useful!

I see in your readme that currently there are four available setting types: `toggle`, `text`, `textarea `and `code`. But a fifth one is mentionned `file`. 

It's currently not working, did you plan to make it works?

**Comment by bakerkretzmar** [comment]
Yes, this is planned but not yet available.

**Comment by philipgunther** [comment]
Any update on the file type?

Many thanks for this great package!
