### ISSUE TITLE
Error After Installing

### ISSUE THREAD

**Issue by jahid56** [bakerkretzmar/nova-settings-tool#25]
Helo I am just install the package. I am doing the required things that is given by you but is shows an error
`Class 'Bakerkretzmar\NovaSettingsTool\SettingsTool' not found`

Also When I publish there is no `nova-settings-tool.php` file in config folder. Could not find where the problem is

**Comment by bakerkretzmar** [comment]
Could you post a full stack trace please?

When you run `php artisan vendor:publish --tag="nova-settings-tool"` what's the output?

Are you installing the package for the first time or upgrading from an earlier version?

Thanks.

**Comment by jahid56** [comment]
No I am installing the package for the first time. When I run `php artisan vendor:publish --tag="nova-settings-tool"` it shows `Publishing complete.`. But there is no file  called `nova-settings-tool.php` in my `config` folder. When I access my website it throws error 
`Class 'Bakerkretzmar\NovaSettingsTool\SettingsTool' not found`

**Comment by bakerkretzmar** [comment]
Please post the _full_ output of the command, and a stack trace for the error.

The imports and `tools` method of your `NovaServiceProvider.php` would be helpful too.

**Comment by jahid56** [comment]
I am just upgrading the version & the Issue solve automatically. Thank You for this amazing packgae
