### ISSUE TITLE
settings input of type number are not working

### ISSUE THREAD

**Issue by jafar690** [bakerkretzmar/nova-settings-tool#26]

**Comment by bakerkretzmar** [comment]
Please be more specific so I know what to look for here, and provide code examples if possible.

**Comment by jafar690** [comment]
@bakerkretzmar the input for the block below doesn't show
```
[
      'key' => 'affiliate_cookie_timeout',
      'name' => 'Affiliate Cookie Timeout (In minutes)',
      'type' => 'number',
      'default' => 43200,
      'description' => 'time out for the affiliate link cookie',
],
```
but if i change the type to text it shows

am using Nova version 2.0.0

**Comment by jafar690** [comment]
@bakerkretzmar i updated to latest version and now everything works
