### ISSUE TITLE
Error after installation (Call to a member function authorize() on string)

### ISSUE THREAD

**Issue by MaxRazen** [bakerkretzmar/nova-settings-tool#29]
Hi. I've installed this package (config is published and tool registered as said in readme)
![OnPaste 20191205-195021](https://user-images.githubusercontent.com/42293858/70255995-beb19b80-1798-11ea-93c3-76c60c82de86.png)

Env:
Laravel v6.6.1
Laravel Nova v2.8.0
Package version 1.0 (on the v0.3.3 the same error)

**Comment by bakerkretzmar** [comment]
Can you post a full stack trace so I can see where the error's actually coming from? Also, what PHP version are you on?

**Comment by MaxRazen** [comment]
I'm very sorry, it's my issue
I tried to register tool using class name `SettingsTool::class,` with this code all works well
```php
    public function tools()
    {
        return [
            new SettingsTool,
        ];
    }
```
