### ISSUE TITLE
Frontend string translations

### ISSUE THREAD

**Issue by Paulsky** [bakerkretzmar/nova-settings-tool#32]
Thank you for this great package! I would like to translate the frontend strings. Like this:

```
'settings' => [
        [
            'key'   => 'twitter_url',
            'label' => 'novaSettingsTool.labels.twitter',
            'panel' => 'novaSettingsTool.panels.social',
        ],
]
```
Then, in `resources/lang/vendor/nova-settings-tool/en.json`
```
{
    "novaSettingsTool.panels.social": "Social settings",
    "novaSettingsTool.labels.twitter": "Twitter Profile"
}
```

Is this possible? Thank you in advance!

**Comment by bakerkretzmar** [comment]
It should be possible, yes—I think you'll want to put your translated strings in `resources/lang/vendor/nova/en.json`. Then what you have above should work. Let me know!

**Comment by Paulsky** [comment]
Thank you @bakerkretzmar . That works! I prefer to have a dedicated translation file though. It's cleaner and easier to find and maintain. Is this possible?

**Comment by bakerkretzmar** [comment]
Glad to hear it! Yes, you can put them in a separate file, you'll need to load that file explicitly.

Assuming your translations are in `resources/lang/en.json`, in the `boot()` method of your `AppServiceProvider`, add something like this:

```php
public function boot()
{
    $this->loadJsonTranslationsFrom(resource_path('lang'));
}
```

You can see how Nova does it [here](https://github.com/laravel/nova/blob/3.0/src/NovaServiceProvider.php#L90).
