### ISSUE TITLE
Hide from navigation

### ISSUE THREAD

**Issue by PrzemekTkaczyk** [bakerkretzmar/nova-settings-tool#33]
Hello, 
First, thank you for creating this package!
Is there any simple option to hide it from navigation (not using roles/permissions) ?

**Comment by bakerkretzmar** [comment]
Who do you want to hide it from? You can probably do this the same way you would with auth:

```php
public function tools()
{
    return [
        (new SettingsTool)->canSee(function ($request) {
            return false;
        }),
    ];
}
```

You can put whatever you want in that closure though, so you could limit it to a specific email or user group or whatever. Let me know if that works!

[Docs](https://nova.laravel.com/docs/3.0/customization/tools.html#authorization)

**Comment by PrzemekTkaczyk** [comment]
Yes, I know this, and there I use speciffic role or permission - for autohorization users,
but I don't want to see it in navigation - because I have custom file for navigation - and now your tool automatically appear on bottom of menu :)
(on all tools I have removed code from "naviagation.blade"

If there is no option - I will create a fork..

**Comment by bakerkretzmar** [comment]
Interesting, how are you rendering a custom navigation? Wouldn't that override everything, including this tool?

**Comment by PrzemekTkaczyk** [comment]
No, it just override nova-view which render navigation:
I just made a file: PROJECT/resources/views/vendor/nova/resources/navigation.blade.php, but all other scripts are working normally, that's why "SETTINGS" are appear on the bottom of menu :)

**Comment by bakerkretzmar** [comment]
Do you have any other tools installed? Do they show up?

**Comment by bakerkretzmar** [comment]
@PrzemekTkaczyk thanks for your patience.

Create a file in your project at `resources/views/vendor/settings-tool/navigation.blade.php`. This will override the sidebar item completely, so to hide it, just leave that file empty.

**Comment by PrzemekTkaczyk** [comment]
Thanks a lot ! :).  👍
