### ISSUE TITLE
Default Package Configuration

### ISSUE THREAD

**Issue by markwalet** [bakerkretzmar/nova-settings-tool#4]
Make it possible for users to just overwrite the configuration options that they need to override.

I will make a PR for this

**Comment by bakerkretzmar** [comment]
How often would you see this being used? My intention was that there's *no* built-in configuration, so we would want the user to always override everything.

The top-level config array items `path` and `navigation` have hard-coded fallbacks if they're not included in a user's config file, and it looks like `mergeConfigFrom` [doesn't play nicely with nested arrays](https://laravel.com/docs/5.7/packages#resources), which I think would rule out doing any merging inside the `panels` array.

**Comment by markwalet** [comment]
I like to keep my own config files clean. Things like paths to the json file are just clutter in my own code imo

**Comment by bakerkretzmar** [comment]
You can take that line out and it will look for `app/settings.json` by default. The [controller falls back to that path](https://github.com/bakerkretzmar/nova-settings-tool/blob/4c5737d3af7e33705f223c8f0bca6eaf53bfd78a/src/Http/Controllers/SettingsToolController.php#L16) if nothing is defined anywhere else. Is that what you're talking about?

**Comment by markwalet** [comment]
Yeah, I meant that. But I think that kind of default behavior should be defined in a default config file.

Maybe it's just a matter of personal taste
