### ISSUE TITLE
Fields are not added to the admin panel.

### ISSUE THREAD

**Issue by Fizik11** [bakerkretzmar/nova-settings-tool#41]
Added fields to nova-settings-tools. Registered with the provider. But in the admin. the panel did not add new fields. What could be the problem? Thank you.

![image](https://user-images.githubusercontent.com/15604710/104821861-19904000-583f-11eb-98c2-bdfddf2d0616.png)

**Comment by bakerkretzmar** [comment]
What do you see in Nova on the tool page?

**Comment by Fizik11** [comment]
> What do you see in Nova on the tool page?

Old fields added by a previous project developer.

**Comment by bakerkretzmar** [comment]
Can you provide more screenshots and code examples please, and the version of Nova and Nova Settings Tool you're using?

Do any of the fields in the config file and the tool page match up, or are they all completely different? Are you able to enable/disable the tool completely by not registering it in your `NovaServiceProvider`?

**Comment by Fizik11** [comment]
Nova settings tools -- 1.1.0.
Version Nova 3.9.4.

Regardless of whether there are fields in the config settings or not, in the admin. the panels don't change anything.

What parts of the code would you like to see? Thank you.

**Comment by Fizik11** [comment]
Okay. I'm very stupid. Just didn't clear the view caches. Sorry for wasting time, I regret it.

**Comment by bakerkretzmar** [comment]
We've all been there 😅 no worries at all, glad you got it working!

**Comment by Fizik11** [comment]
Thanks for the help!  I will gain experience and learn from my mistakes.  :)

ср, 20 янв. 2021 г., 3:14 AM Jacob Baker-Kretzmar <notifications@github.com
