### ISSUE TITLE
Not compatible with Nova 4.0

### ISSUE THREAD

**Issue by olivervo** [bakerkretzmar/nova-settings-tool#45]
Package does not seem to be compatible with the lastest version of Nova 4.0.

`[2022-04-06 11:10:18] local.ERROR: Class Bakerkretzmar\NovaSettingsTool\SettingsTool contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)
`

**Comment by scramatte** [comment]
+1 here

**Comment by olivervo** [comment]
I can open the settings page one now however the sidebar is gone. If I then refresh the page I get 404 not found. The issue remains if I paste in your default config file. @bakerkretzmar

**Comment by bakerkretzmar** [comment]
What do you mean the sidebar is gone? Like the whole sidebar disappears, or "Settings" is missing from it?

**Comment by olivervo** [comment]
The whole sidebar disappears, see screenshots below. I'm not getting any errors in the logs or console. The last image is of the main control panel where the sidebar is gone after visiting the settings page. If the page is refreshed once again it comes back.

<img width="1662" alt="Skärmavbild 2022-04-18 kl  01 17 53" src="https://user-images.githubusercontent.com/6323794/163735905-c8246f93-4e16-4d09-a64e-6b72a0ab2e92.png">
<img width="1660" alt="Skärmavbild 2022-04-18 kl  01 18 02" src="https://user-images.githubusercontent.com/6323794/163735907-1cf770b2-2d25-45a4-b970-c24ad9e60302.png">
<img width="1660" alt="Skärmavbild 2022-04-18 kl  01 18 13" src="https://user-images.githubusercontent.com/6323794/163735908-baf7fbdc-09aa-4d42-88e6-07f60ae651e4.png">

**Comment by bakerkretzmar** [comment]
Ugh okay thanks, I'll look into this. I have a feeling it's Nova, not this tool. I've noticed similar weird stuff just navigating around my own Nova app, but with the page content, not the sidebar.
