### ISSUE TITLE
Do this module support settings per user?

### ISSUE THREAD

**Issue by scramatte** [bakerkretzmar/nova-settings-tool#47]
Hello,

Do this module support settings per user?
I mean using some json column settings into user table for example

Regards

**Comment by olivervo** [comment]
This package saves settings as JSON in a text file - not in the database. It's theoretically possible to store an entry with each user's ID and respective setting but depending on your number of users this probably isn't the best option.

This package might be closer to what you're looking for if you want to store permissions:
https://github.com/spatie/laravel-permission

**Comment by bakerkretzmar** [comment]
@olivervo is correct—no, this package doesn't support per-user settings. If you're storing user settings in a JSON column on the `users` table you're better off with a package, or, depending how complicated your settings are, just [Laravel's built-in `AsArrayObject` or `AsCollection` cast objects](https://laravel.com/docs/9.x/eloquent-mutators#array-object-and-collection-casting).
