### ISSUE TITLE
Resource page does not show after visit setting page

### ISSUE THREAD

**Issue by sadovyiov** [bakerkretzmar/nova-settings-tool#48]
Hi, 
When I visit the setting page, it works correctly, but after changing the location to a different resource, it is empty. After refreshing the resource page it is showing.

Nova v4
Opera 86/Firefox 100

Video - https://share.cleanshot.com/lFIu5F

**Comment by itinnovative** [comment]
I had the same issue.  Traced it back to a bad template in Tool.vue.  Wrap the entire inner contents of the template in a div and recompile.  Created a pull request for this.  This resolves the issue for me.

**Comment by olivervo** [comment]
Sounds like a similar issue to [this](https://github.com/bakerkretzmar/nova-settings-tool/issues/45).
