### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by aliwesome** [bakerkretzmar/nova-settings-tool#50]
I just faced this issue on the console after installing the package on Nova 4.X.

**Comment by bakerkretzmar** [comment]
Can you provide more details please? What page, the complete error, more info about your environment, etc.

**Comment by aliwesome** [comment]
@bakerkretzmar on tool page: `/nova/settings` 
with below console error:
![image](https://user-images.githubusercontent.com/21131502/177400756-ca190f7b-841a-4988-8e85-0b6f33947ae4.png)

**Comment by bakerkretzmar** [comment]
@aliwesome can you update to v2.0.1 and let me know if this is still an issue?

**Comment by aliwesome** [comment]
@bakerkretzmar issue still exists, using it on `Nova 4.12.12 `

**Comment by bakerkretzmar** [comment]
@aliwesome can you try v2.0.2? I think I found the issue here, has to do with a `code` field with no value. Thanks.

**Comment by aliwesome** [comment]
@bakerkretzmar I tried this version out and the issue was fixed. thank you.
