### ISSUE TITLE
Show/hide fields based on permissions?

### ISSUE THREAD

**Issue by salmanhijazi** [bakerkretzmar/nova-settings-tool#51]
Hello,

Are you possibly looking into field level permissions? I've narrowed access to by using canSee in the Service Provider level, but there are some fields that I would really not let anyone but the super admin be able to change.

Also, maybe make panels collapsible or be split into sub-pages and show up as sub-menu items in the navigation bar?

Thanks for the great package!
Cheers

**Comment by bakerkretzmar** [comment]
Per-field permissions is a really interesting idea, I'd be open to a PR for that for sure. Same for making panels collapsible!

Not sure about submenu items and different pages, that feels a lot more complicated.

Thanks for the suggestions!
