### ISSUE TITLE
Error authorizing tool using gate

### ISSUE THREAD

**Issue by olivervo** [bakerkretzmar/nova-settings-tool#52]
I'm having an issue authorizing the package using the canSee method and a gate.

```
NovaServiceProvider.php

SettingsTool::make()->canSee(
                function ($request) {
                    return $request->user()->can('permissions.admin');
                }
            ),
```
The tool is visible in the side menu which would imply that the authorization is working. However once clicked on it gives a 500 error and `Call to a member function can() on null` is logged meaning `$request->user()` is returning null. 

It seems like something is happening behind the scenes on click which doesn't pass canSee the correct $request? Using the `Auth::user()` results in the same error. Testing with other packages don't result in the same error.

**Comment by bakerkretzmar** [comment]
I can't reproduce this, are you absolutely sure the `can()` function that's returning null is _that_ one, in that exact spot? What is the entire stack trace of the error you're getting?

**Comment by olivervo** [comment]
Here is the full stack trace: https://flareapp.io/share/x7Xk2vOP#F66

The error is occurring with no other nova packages/tools so I can't figure out what else it would be.

**Comment by bakerkretzmar** [comment]
Can you create a repo with a reproduction of that error? The code you shared in this issue works in a new app.

In that stack trace I can see that the error is happening at the `/nova/settings` URL but the `canSee()` and `authorizedToSee()` methods in the stack trace are part of Nova itself, I'm not overriding them.

Is your app doing anything that would change the behaviour of `$request->user()`? Is your Nova installation using any kind of custom auth stuff? What does your `permissions.admin` Gate actually look like?

**Comment by nikuscs** [comment]
Indeed the gate is weird, can confirm $request->user() is null for canSee(), in my case im using different guards for the nova panel, so might be the issue.

**Comment by olivervo** [comment]
Finally figured it out - `$request->user()` returns the user using the default guard defined in `config/auth.php`. In my case Nova is not using the default guard thus null was being returned.

To solve this specify the guard used by Nova: `$request->user('guard-name')`.
