### ISSUE TITLE
Styling issue in Nova ^v4.26.5

### ISSUE THREAD

**Issue by everzel** [bakerkretzmar/nova-settings-tool#56]
Hi! I have a problem with styles:

Nova v4.26.5:

![image](https://github.com/bakerkretzmar/nova-settings-tool/assets/91853349/ad1b6b81-e83e-430b-b5fb-95e135de495f)

Nova v4.22.0:
![image](https://github.com/bakerkretzmar/nova-settings-tool/assets/91853349/e72fc6a0-a1fc-45e3-b66c-2e37dc615f1e)

**Comment by bakerkretzmar** [comment]
Thanks. Nova removed some classes I was using, and I can't just install Tailwind and generate all my own styles because Nova's CSS build is broken so doing that breaks the whole app. Fixed in v2.0.4, which I just tagged.
