### ISSUE TITLE
Save button not active

### ISSUE THREAD

**Issue by kombimedia** [bakerkretzmar/nova-settings-tool#6]
Hi @bakerkretzmar ,

Great looking tool, love it! However, the save button in each of my panels is text only i.e not a button nor a link. Any ideas what might be causing this issue?

Cheers,

<img width="2298" alt="screen shot 2019-02-15 at 10 06 41 am" src="https://user-images.githubusercontent.com/28551935/52817826-ea7c6b80-3109-11e9-9b81-1bc118e32cb9.png">

**Comment by bakerkretzmar** [comment]
What Nova version, browser, and OS are you on? That button uses Nova's own `progress-button` component; do the buttons in the rest of your Nova install work normally? Could you provide the HTML source for the button in that screenshot that doesn't do anything?

**Comment by kombimedia** [comment]
Hi Jacob,

Thanks for coming back to me.

Nova version: v1.3.2
Browser: Google Chrome v72.0.3626.109 (Official Build) (64-bit) - same issue in Safari and Firefox
OS: macOS Mojave v10.14.2

<progress-button class="ml-auto">
   Save
</progress-button>

The progress buttons work fine in the rest of Nova install.

Thanks for your help with this Jacob.

Cheers

**Comment by bakerkretzmar** [comment]
Ok, I think it might be something else with Vue or Nova that's causing this. The `progress-button` component isn't being picked up and rendered by Vue, but it's part of Nova. That HTML should look like this:

```html
<div class="bg-30 flex px-8 py-4">
    <button type="button" class="btn btn-default btn-primary inline-flex items-center relative ml-auto">
        <span class="">Save</span>
    </button>
</div>
```

My setup is the same as yours except that I'm on macOS 10.13, but that shouldn't matter, and it's working for me on a fresh install in an empty site.

Are you getting any errors in the console? Do you have any toggle settings and are they working? If you're using Vue devtools, do they shed any light? Have you tried [republishing your Nova assets](https://nova.laravel.com/docs/1.0/installation.html#updating-nova)?

Was it like this right when you installed or did it work at first? What does you config file look like?

The more I know the better I can look into this :)

**Comment by kombimedia** [comment]
Hi Jacob,

All sorted! Was a local issue. I republished my Nova assets and she’s all go.

Thank you so much for your help with this!

Cheers
