### ISSUE TITLE
Proposition: Settings usage

### ISSUE THREAD

**Issue by antongorodezkiy** [bakerkretzmar/nova-settings-tool#7]
Maybe we can add something like the following approach to use saved settings from inside of the app?
I'm using the following code to get settings by their keys with the standard Laravel's `config()` helper.

`app/Providers/AppServiceProvider.php`
```
<?php

namespace App\Providers;

use Cache;

use Illuminate\Support\ServiceProvider;

use Spatie\Valuestore\Valuestore;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // dynamic settings
        $cacheKey = __CLASS__.':'.__FUNCTION__.':dynamicSettings';
        $settings = Cache::remember($cacheKey, 1, function() {
            return Valuestore::make( storage_path(config('settings.path', 'app/settings.json')) )->all();
        });

        foreach ($settings as $key => $value) {
            config(['setting.'.$key => $value]);
        }
    }
}
```

**Comment by bakerkretzmar** [comment]
Thanks for the suggestion! This package is just a tool to manage settings through Nova and I want to keep it focused on just that one thing, so fetching and using the settings elsewhere in your app is a job for another package.

[This article on Laravel News](https://laravel-news.com/global-application-settings) by Tim MacDonald gave me the idea for this package, and his approach is what I'm doing to use the settings throughout my apps.
