### ISSUE TITLE
Incompatibility with anlutro/laravel-settings

### ISSUE THREAD

**Issue by hubertnnn** [bakerkretzmar/nova-settings-tool#8]
Since this package looks like a perfect pair for `anlutro/laravel-settings` it would be nice to make them work together.

The issue is that both packages use a common config option: `settings.path`.
Anluro is providing it as a full path (`'path' => storage_path().'/app/settings.json',`).
Your package is using just a subfolder path (`'path' => 'app/settings.json',`).

Since laravel itself resolves paths in config files (eg. cache.php has `'path' => storage_path('framework/cache/data'),`) I think this package should have its config changed to reach compatibility.

As a bonus it will make it possible to put config in more places than just storage if needed.

**Comment by bakerkretzmar** [comment]
Thanks for this! I didn't realize I could resolve paths inside the config file, is there any benefit to doing it that way? My package does use `storage_path()` to resolve whatever path is passed in from the config.

To make this package compatible with anlutro's, I would have to actually change the name of the published config file, right? That would be a breaking change so I don't think I can promise it any time soon. In hindsight I probably should have chosen something a little more specific than 'settings' as a config file name, so I'll look at fixing that if I release another major version.

**Comment by bakerkretzmar** [comment]
This should be resolved in v1.
